### ISSUE TITLE
LaunchWrapper crashes with NEI on r1.2.5

### ISSUE THREAD

**Issue by DanyGames2014** [MCPHackers/LaunchWrapper#12]
When using LaunchWrapper on Release 1.2.5 with Forge and NEI, the game crashes when opening inventory with the following error

My setup:
- Legacy LWJGL 3 1.0-SNAPSHOT
- LWJGL 3.3.3
- Minecraft 1.2.5
- Forge 3.4.9.171 patched to disable title check which fails and crashes with LW
- CodeChickenCore 0.5.5
- NotEnoughItems 1.3.0.1
- Launchwrapper 1.0-SNAPSHOT

[PrismLauncher Instance](https://github.com/user-attachments/files/16979723/1.2.5.Pack.zip)

```
java.lang.NullPointerException
	at codechicken.nei.NEIConfig.getSearchExpression(NEIConfig.java:544)
	at codechicken.nei.NEIUtils.loadItems(NEIUtils.java:74)
	at codechicken.nei.NEIController.<init>(NEIController.java:23)
	at gb.a(GuiContainer.java:60)
	at net.minecraft.client.Minecraft.a(Minecraft.java:641)
	at net.minecraft.client.Minecraft.k(Minecraft.java:1747)
	at net.minecraft.client.Minecraft.x(Minecraft.java:825)
	at net.minecraft.client.Minecraft.run(Minecraft.java:753)
	at java.lang.Thread.run(Thread.java:750)
2024-09-12 14:55:45 [SEVERE] A critical error has occurred.
java.lang.NullPointerException
	at codechicken.nei.NEIConfig.getSearchExpression(NEIConfig.java:544)
	at codechicken.nei.NEIUtils.loadItems(NEIUtils.java:74)
	at codechicken.nei.NEIController.<init>(NEIController.java:23)
	at gb.a(GuiContainer.java:60)
	at net.minecraft.client.Minecraft.a(Minecraft.java:641)
	at net.minecraft.client.Minecraft.k(Minecraft.java:1747)
	at net.minecraft.client.Minecraft.x(Minecraft.java:825)
	at net.minecraft.client.Minecraft.run(Minecraft.java:753)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by Lassebq** [comment]
I don't think forge works the way it's supposed to under LaunchWrapper
```2024-09-12 21:34:40 [SEVERE] 0 mods loaded```
You're also getting this in your log right?

**Comment by Lassebq** [comment]
Try 20b443209e7ef253d44764539143e3a5f268e73e
